; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=armv7-unknown-linux-gnueabihf -mattr=+vfp3,+d16 -verify-machineinstrs -o - %s | FileCheck %s
;
; Test ARM32 Statepoint / StackMap / PatchPoint support.
; These are required by the GraalVM LLVM backend (-H:CompilerBackend=llvm)
; for ARM32 (ARMv7/EABIHF) native-image generation.
;
; See: BOXP-152 (GraalVM ARM32 native-image support via LLVM backend)

; Test basic stackmap emission on ARM32
; CHECK-LABEL: test_stackmap:
; CHECK: .section .llvm_stackmaps
define void @test_stackmap(i64 %p1, i64 %p2) {
entry:
  call void (i64, i32, ...) @llvm.experimental.stackmap(i64 1, i32 4)
  ret void
}

; Test basic statepoint on ARM32
; CHECK-LABEL: test_statepoint:
define i32 addrspace(1)* @test_statepoint(i32 addrspace(1)* %ptr) gc "statepoint-example" {
entry:
  ; Simple statepoint: call a function with a GC pointer live
  %tok = call token (i64, i32, void ()*, i32, i32, ...) @llvm.experimental.gc.statepoint.p0f_isVoidf(
      i64 0, i32 0, void ()* @foo, i32 0, i32 0,
      i32 addrspace(1)* %ptr)
  %ptr2 = call i32 addrspace(1)* @llvm.experimental.gc.relocate.p1i32(token %tok, i32 0, i32 0)
  ret i32 addrspace(1)* %ptr2
}

declare void @foo()
declare void @llvm.experimental.stackmap(i64, i32, ...)
declare token @llvm.experimental.gc.statepoint.p0f_isVoidf(i64, i32, void ()*, i32, i32, ...)
declare i32 addrspace(1)* @llvm.experimental.gc.relocate.p1i32(token, i32, i32)
